AllCops:
  TargetRubyVersion: 2.6
  NewCops: enable

Layout/LineLength:
  Max: 120

Metrics/BlockLength:
  Exclude:
  - "*.gemspec"
  - "spec/**/*"

Metrics/MethodLength:
  Enabled: false

Naming/PredicatePrefix:
  AllowedMethods:
    - does_not_match?

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes
