AllCops:
  TargetRubyVersion: 2.6

Metrics/BlockLength:
  Exclude:
  - "*.gemspec"
  - "spec/**/*"

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Layout/LineLength:
  Max: 120
